// <auto-generated />
using System;
using FullCRUD.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FullCRUD.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220610144109_CurdTable")]
    partial class CurdTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FullCRUD.Models.CrudModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AMCRenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AMCRenewalPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("DomainRenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DomainRenewalPrice")
                        .HasColumnType("int");

                    b.Property<int>("HostingRenewalPrice")
                        .HasColumnType("int");

                    b.Property<DateTime>("HostingRenwalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SEORenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SEORenewalPrice")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CrudModel");
                });
#pragma warning restore 612, 618
        }
    }
}
